# numpy_exercises

## Use the following code for the questions below:

In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?
2. How many positive numbers are there?
3. How many even positive numbers are there?
4. If you were to add 3 to each data point, how many positive numbers would there be?
5. If you squared each number, what would the new mean and standard deviation be?


In [6]:
#1 
print(len(a[a< 0]))

4


In [7]:
#2
print(len(a[a>0]))

5


In [8]:
#3
print(len(a[(a>0) & (a%2==0)]))

3


In [11]:
#4
a +=3
print(len(a[(a>0) & (a%2==0)]))
a

7


array([10, 16, 18, 29,  4,  5,  6,  6,  6,  0,  9, -1])

In [14]:
#5
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
print(a.mean())
print(a.std())
a=a**2
print(a.mean())
print(a.std())

3.0
8.06225774829855
74.0
144.0243035046516


 6. A common statistical operation on a dataset is centering. 
- This means to adjust the data such that the mean of the data is 0. 
- This is done by subtracting the mean from each data point. Center the data set. 
- See this link for more on centering.
 7. Calculate the z-score for each data point. Recall that the z-score is given by:
- Z =(x−μ)/σ
 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [19]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

cent=a-a.mean()
print(cent)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [20]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a=cent/a.std()
print(a)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


## import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Use python's built in functionality/operators to determine the following:
### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

In [21]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [26]:
sum_of_a = sum(a)
print(sum_of_a)

55


In [28]:
min_of_a = min(a)
print(min_of_a)

1


In [30]:
max_of_a = max(a)
print(max_of_a)

10


In [33]:
import numpy as np

In [34]:
mean_a = a.mean()
print(mean_a)

AttributeError: 'list' object has no attribute 'mean'

In [35]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [36]:
mean_a = a.mean()
print (mean_a)

5.5


In [37]:
import math
product_a = math.prod(a)
print(product_a)

3628800


In [38]:
square_a = a**2
print(square_a)

[  1   4   9  16  25  36  49  64  81 100]


In [41]:
# attempt 1
odd_a = [n for n in a if n % 2 != 0]
print(odd_a)

[1, 3, 5, 7, 9]


In [43]:
evens_a = [n for n in a if n%2==0]
print(evens_a)

[2, 4, 6, 8, 10]


# Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
- b = [
-   [3, 4, 5],
-   [6, 7, 8]
- ]

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

### Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


### Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


### Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


### Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

### Exercise 9 - print out the shape of the array b.

### Exercise 10 - transpose the array b.

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [71]:
#1
b = np.array ([
    [3, 4, 5],
    [6, 7, 8]
])

In [48]:
#2
sum_b = b.sum()
print(sum_b)

33


In [49]:
#n/a - got carried away
min_b = b.min()
print(min_b)

3


In [50]:
#3
max_b = b.max()
print(max_b)

8


In [51]:
#4
mean_b = b.mean()
print(mean_b)

5.5


In [55]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
prod_b = np.prod(b)
print(prod_b)

20160


In [54]:
#6
square_b = np.square(b)
print(square_b)

[[ 9 16 25]
 [36 49 64]]


In [69]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
mask_even = b % 2 != 0
mask_even
b[mask_even]

array([3, 5, 7])

In [76]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
print(b)
mask_odd = b % 2 == 0
b[mask_odd]

[[3 4 5]
 [6 7 8]]


array([4, 6, 8])

In [77]:
# 9 Exercise 9 - print out the shape of the array b.
b.shape

(2, 3)

In [79]:
# Exercise 10 - transpose the array b.
print(b.transpose())

[[3 6]
 [4 7]
 [5 8]]


In [80]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
print(np.concatenate(b))

[3 4 5 6 7 8]


In [88]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
print(np.transpose(np.concatenate(b))

SyntaxError: unexpected EOF while parsing (887335644.py, line 2)

# Setup 3
- c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

## HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
## Exercise 1 - Find the min, max, sum, and product of c.

## Exercise 2 - Determine the standard deviation of c.

## Exercise 3 - Determine the variance of c.

## Exercise 4 - Print out the shape of the array c

## Exercise 5 - Transpose c and print out transposed result.

## Exercise 6 - Get the dot product of the array c with c. 

## Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

## Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [89]:
# Set up
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [91]:
# 1.
c=np.array(c)
print(c.min())
print(c.max())
print(c.sum())
print(np.prod(c))

1
9
45
362880


In [92]:
#2
print(c.std())

2.581988897471611


In [93]:
#3
print(np.var(c))

6.666666666666667


In [94]:
#4
print(c.shape)

(3, 3)


In [95]:
#5
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [96]:
#6
print(np.dot(c,c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [97]:
#7
print((c*c.transpose()).sum())

261


In [99]:
#8
print(np.prod(c*c.transpose()))

131681894400


# Setup 4
## d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

### Exercise 1 - Find the sine of all the numbers in d

### Exercise 2 - Find the cosine of all the numbers in d

### Exercise 3 - Find the tangent of all the numbers in d

### Exercise 4 - Find all the negative numbers in d

### Exercise 5 - Find all the positive numbers in d

### Exercise 6 - Return an array of only the unique numbers in d.

### Exercise 7 - Determine how many unique numbers there are in d.

### Exercise 8 - Print out the shape of d.

### Exercise 9 - Transpose and then print out the shape of d.

### Exercise 10 - Reshape d into an array of 9 x 2

In [109]:
#set up
d = [
[90, 30, 45, 0, 120, 180],
[45, -90, -30, 270, 90, 0],
[60, 45, -45, 90, -45, 180]
]

d=np.array(d)

In [101]:
# 1
print(np.sin(d))

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


In [102]:
#2
print(np.cos(d))

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


In [103]:
#3
print(np.tan(d))

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


In [110]:
#4
d[d < 0]

array([-90, -30, -45, -45])

In [111]:
#5
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [112]:
#6
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [114]:
#7
len(np.unique(d))

11

In [115]:
#8
print(d.shape)

(3, 6)


In [116]:
#9
print(d.transpose().shape)

(6, 3)


In [117]:
#10
print(d.reshape(9,2))

[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
